version = 1

[[annotations]]
path = [
    "PocketTSLM.xcodeproj/**",
    "PocketTSLM/Supporting Files/**",
    "PocketTSLM.xctestplan",
    "PocketTSLMTestPlan.xctestplan",
    "Analysis/**",
    "PocketTSLMStudy/Supporting Files/**",
]
SPDX-FileCopyrightText = "2026 The Authors and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"